-- AlterTable
ALTER TABLE "events" ALTER COLUMN "country" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "country_code" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "country_code_iso3" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "country_subdivision" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "free_form_address" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "local_name" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "municipality" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "poi_name" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "postal_code" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "street_name" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "street_number" SET DATA TYPE VARCHAR(500);
