// never change the order of these
export const categories = [
  { name: "UiO" },
  { name: "Blindern" },
  { name: "IFI" },
  { name: "Bedriftspresentasjon" },
  { name: "Mat" },
  { name: "Alkohol" },
  { name: "Dansing" },
  { name: "LGBTQ+" },
  { name: "Fest" },
  { name: "Utendørs" },
  { name: "Kultur" },
  { name: "Kaffe" },
  { name: "Natur" },
  { name: "Trening" },
  { name: "Spill" },
  { name: "Musikk" },
];

export const allergens = [
  { name: "Gluten" },
  { name: "Skalldyr" },
  { name: "Egg" },
  { name: "Fisk" },
  { name: "Peanøtter" },
  { name: "Soya" },
  { name: "Melk" },
  { name: "Nøtter" },
  { name: "Selleri" },
  { name: "Sennep" },
  { name: "Sesamfrø" },
  { name: "Svoveldioksid og sulfitter" },
  { name: "Lupin" },
  { name: "Bløtdyr" },
];
