export const MCP_TOOL_SUMMARIES: Record<string, string> = {
  who_am_i: "Hvilken Peoply-konto nøkkelen tilhører.",
  search_events: "Søk i offentlige arrangementer.",
  get_event: "Hent ett arrangement du har tilgang til.",
  search_organizations: "Søk i godkjente foreninger.",
  get_organization: "Hent én godkjent forening.",
  list_my_registrations: "Arrangementene du er påmeldt.",
  list_my_favorites: "Arrangementene du har favorittmerket.",
  list_my_organizations: "Foreningene du har en rolle i.",
  list_my_arranged_events: "Arrangementene du selv arrangerer.",
  list_my_notifications: "Invitasjoner som venter på svar.",
  list_followed_organizers: "Arrangørene du følger.",
  register_for_event: "Meld deg på et offentlig arrangement.",
  update_my_registration: "Endre eller meld deg av en påmelding.",
  favorite_event: "Favorittmerk et arrangement.",
  unfavorite_event: "Fjern et arrangement fra favorittene.",
  follow_organizer: "Følg en arrangør.",
  unfollow_organizer: "Slutt å følge en arrangør.",
  create_event: "Opprett et arrangement, uten bilde.",
  list_event_registrations: "Se påmeldte på et arrangement du arrangerer.",
};
