export const RELATION_TARGET_MODELS: Record<string, string> = {
  "User.registrations": "Registration",
  "User.eventInvitationsToMe": "EventInvitation",
  "User.eventInvitationsFromMe": "EventInvitation",
  "UserOrganizationRole.organization": "Organization",
  "Arranger.organization": "Organization",
  "Arranger.arrangerFollowerEvents": "ArrangerFollowerEvent",
  "Event.registrations": "Registration",
  "Event.eventInvitations": "EventInvitation",
  "OrganizationIcsFeed.organization": "Organization",
  "OrganizationIcsFeed.importedEvents": "Event",
  "OrganizationReport.organization": "Organization",
  "EventUpdate.event": "Event",
  "EventArranger.event": "Event",
  "Registration.event": "Event",
  "EventCategory.event": "Event",
  "Favorite.event": "Event",
  "EventInvitation.event": "Event",
  "OrganizationInvitation.organization": "Organization",
  "EventCoOrganizerInvitation.event": "Event",
  "EventCoOrganizerInvitation.organization": "Organization",
};
