name: Build and test Node.js app

env:
  NODE_VERSION: '20.x'
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        run: npm install
      - name: npm lint
        run: npm run lint --if-present
      - name: npm build
        run: npm run build --if-present
      - name: npm test
        run: npm run test --if-present
